### PR TITLE
README: Fix more typos

### PR DESCRIPTION
**Pull request by DeathlyPlays**

### CODE REVIEW

**Comment by Mystifi** [comment]
Several of these typos are repeated throughout repository code, especially the typo with "inappropriate." It might be worth checking for them in the source?

**Comment by DeathlyPlays** [comment]
Perhaps @Mystifi afaik Ecuacion isn't resuming coding this so I might try continuing on a new repo adding more to this

**Comment by TheRun98** [comment]
Please do, there have been issues from `Object.merge` lately. If its done I can definitely try to help contribute.

**Comment by DeathlyPlays** [comment]
@TheRun98 I used the recent pr's made that work and added them to my github for this as well like #68

**Comment by DeathlyPlays** [comment]
Meh I'll add #67 as well

**Comment by Mystifi** [comment]
> Please do, there have been issues from Object.merge lately.

@TheRun98, you should be able to use `Object.assign` everywhere `Object.merge` is used because the latter is simply sugar.

**Pull request closed without merging**
